{{- range .Values.baseApps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.argocdNamespace }}
spec:
  project: default
  source:
    chart: {{ .chart }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ .targetRevision }}
    helm:
      releaseName: {{ .name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}