apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plaid-service
  namespace: {{ .Values.argocdNamespace }}
spec:
  project: default
  source:
    chart: python
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: plaid-service
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true