{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "angular.fullname" . }}
  labels:
    app: {{ template "angular.name" . }}
    chart: {{ template "angular.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations: {{ .Values.ingress.annotations | toYaml | nindent 4  }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: {{ $.Values.ingress.path }}(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ template "angular.fullname" $ }}
              port:
                number: {{ $.Values.service.port }}
  {{- end -}}
{{- end -}}