argocdNamespace: argocd

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://zbialik.github.io/my-finance-helm

baseApps:
  - name: my-finance-ui
    namespace: frontend
    chart: angular
    targetRevision: ">=0.0.0"
  - name: plaid-service
    namespace: backend
    chart: python
    targetRevision: ">=0.0.0"